theme: jekyll-theme-minimal
logo: IMG_4520.HEIC

author :
  name : Raymond Lui
  github : luzray56
  linkedin: raymond-lui-329272198
  
title: Hi, I'm Raymond!
description: A website to showcase my projects and highlights

markdown: kramdown
