theme: jekyll-theme-minimal
logo: IMG_4520 (1).jpg

author :
  name : Raymond Lui
  github : luzray56
  
title: Raymond Lui
description: A website to showcase my projects and highlights

markdown: kramdown
