theme: jekyll-theme-minimal
logo: IMG_4520 (1).jpg

author :
  name : Raymond Lui
  github : luzray56
  
title: Raymond Lui
description: My personal website!

sidebar:
  title: "Sample Title"
  nav: sidebar-sample
  
sidebar-sample:
  - title: "Parent Page A"
    children:
      - title: "Child Page A1"
        url: /contact.md

markdown: kramdown
