theme: jekyll-theme-minimal
logo: IMG_4520 (1).jpg

author :
  name : Raymond Lui
  github : luzray56
  
title: Raymond Lui
description: My personal website!

sidebar_home_link: true

nav:
- name:     "Contact"
  url:      "/contact"
- name:     "Teaching"
  url:      "/teaching"

markdown: kramdown
