theme: jekyll-theme-minimal
logo: IMG_4520 (1).jpg

author :
  name : Raymond Lui
  github : luzray56
  
title: Raymond Lui
description: [Teaching](https://luzray56.github.io/teaching)\[Contact](https://luzray56.github.io/contact)\[Resume](https://luzray56.github.io/Resume%20(2021).pdf)

markdown: kramdown
