theme: jekyll-theme-minimal
logo: IMG_4520 (1).jpg

author :
  name : Raymond Lui
  github : luzray56
  
title: Raymond Lui
description: My personal website!

docs_list_title: ACME Documentation
docs:
- title: Contact
  url: contact.md

- title: Teaching
  url: teaching.md

markdown: kramdown
